import os
import glob

##########################################################################
# Things to build

# TEX files that should become PDF files (via latex)
TEX_FILES = [os.path.splitext(fn)[0] for fn in glob.glob("*.tex")]
TEX_FILES.sort()  # Let's always build in the same order

##########################################################################
# Setup builders and environment

env = Environment(  # NOQA
    ENV=os.environ
)

##########################################################################
# Add builders and dependecies to environment

for base in TEX_FILES:
    pdf = env.PDF(target=base + ".pdf", source=base + ".tex")
